[package]
name = "lox-vm"
version = "0.1.0"
authors = ["Roman Amici <amicir@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

num_enum = "0.5.1"
rustyline = "8.0.0"
lazy_static = "1.4.0"